"""All Races preference scheme.

Maps all human/elf/orc vanilla races to furry equivalents.
Dogs for humans, cats for elves/orcs.
Ported from BDFurrySkyrim_Preferences_AllRaces.pas.
"""

from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from furrifier.race_defs import RaceDefContext


def configure(ctx: RaceDefContext):
    """Configure race assignments for the All Races scheme."""

    # =========== NORD ===========
    ctx.set_race('NordRace', 'YASLykaiosRace', 'DOG')
    ctx.set_race('NordRaceVampire', 'YASLykaiosRaceVampire', 'DOG')
    ctx.set_race('NordRaceChild', 'YASLykaiosRaceChild', 'DOG')
    ctx.set_race('DLC1NordRace', 'YASLykaiosRace', 'DOG')
    ctx.set_race('NordRaceAstrid', 'YASLykaiosRace', 'DOG')

    # =========== ELDER ===========
    ctx.set_race('ElderRace', 'YASLykaiosRace', 'DOG')
    ctx.set_race('ElderRaceVampire', 'YASLykaiosRaceVampire', 'DOG')

    # =========== IMPERIAL ===========
    ctx.set_race('ImperialRace', 'YASKettuRace', 'DOG')
    ctx.set_race('ImperialRaceChild', 'YASKettuRaceChild', 'DOG')
    ctx.set_race('ImperialRaceVampire', 'YASKettuRaceVampire', 'DOG')

    # =========== BRETON ===========
    ctx.set_race('BretonRace', 'YASKygarraRace', 'DOG')
    ctx.set_race('BretonRaceChild', 'YASKygarraRaceChild', 'DOG')
    ctx.set_race('BretonRaceVampire', 'YASKygarraRaceVampire', 'DOG')
    ctx.set_race('BretonRaceChildVampire', 'YASKettuRaceChildVampire', 'DOG')

    # =========== REDGUARD ===========
    ctx.set_race('RedguardRace', 'YASXebaRace', 'DOG')
    ctx.set_race('RedguardRaceChild', 'YASXebaRaceChild', 'DOG')
    ctx.set_race('RedguardRaceVampire', 'YASXebaRaceVampire', 'DOG')

    # =========== REACHMAN (subrace of Breton) ===========
    ctx.set_subrace('YASReachmanRace', 'Reachmen', 'BretonRace', 'YASKonoiRace', 'DOG')
    ctx.set_subrace('YASReachmanRaceVampire', 'Reachmen', 'BretonRaceVampire', 'YASKonoiRaceVampire', 'DOG')
    ctx.set_subrace('YASReachmanRaceChild', 'Reachmen', 'BretonRaceChild', 'YASKonoiRaceChild', 'DOG')
    ctx.set_faction_race('ForswornFaction', 'YASReachmanRace')
    ctx.set_faction_race('MS01TreasuryHouseForsworn', 'YASReachmanRace')
    ctx.set_faction_race('DruadachRedoubtFaction', 'YASReachmanRace')

    # =========== SKAAL (subrace of Nord) ===========
    ctx.set_subrace('YASSkaalRace', 'Skaal', 'NordRace', 'YASVaalsarkRace', 'DOG')
    ctx.set_subrace('YASSkaalRaceChild', 'Skaal', 'NordRaceChild', 'YASVaalsarkRaceChild', 'DOG')
    ctx.set_subrace('YASSkaalRaceVampire', 'Skaal', 'NordRaceVampire', 'YASVaalsarkRaceVampire', 'DOG')
    ctx.set_faction_race('DLC2SkaalVillageCitizenFaction', 'YASSkaalRace')

    # =========== HIGH ELF ===========
    ctx.set_race('HighElfRace', 'YASMahaRace', 'CAT')
    ctx.set_race('HighElfRaceVampire', 'YASMahaRaceVampire', 'CAT')

    # =========== WOOD ELF ===========
    ctx.set_race('WoodElfRace', 'YASDumaRace', 'CAT')
    ctx.set_race('WoodElfRaceVampire', 'YASDumaRaceVampire', 'CAT')

    # =========== DARK ELF ===========
    ctx.set_race('DarkElfRace', 'YASKaloRace', 'CAT')
    ctx.set_race('DarkElfRaceVampire', 'YASKaloRaceVampire', 'CAT')

    # =========== ORC ===========
    ctx.set_race('OrcRace', 'YASBaghaRace', 'CAT')
    ctx.set_race('OrcRaceVampire', 'YASBaghaRaceVampire', 'CAT')

    # =========== SNOW ELF ===========
    ctx.set_race('SnowElfRace', 'YASShanRace', 'CAT')

    # =========== WINTERHOLD (subrace of Nord, assigned cat) ===========
    ctx.set_subrace('YASWinterholdRace', 'Winterhold Denizen', 'NordRace', 'YASShanRace', 'CAT')
    ctx.set_faction_race('TownWinterholdFaction', 'YASWinterholdRace')
    ctx.set_faction_race('CrimeFactionWinterhold', 'YASWinterholdRace')

    # =========== SAILORS (subrace of Nord, assigned cat) ===========
    ctx.set_subrace('YASSailorRace', 'Sailor', 'NordRace', 'CellanRace', 'CAT')
    ctx.set_faction_race('DawnstarFishingShipFaction', 'YASSailorRace')
    ctx.set_faction_race('DawnstarImperialShipFaction', 'YASSailorRace')
    ctx.set_faction_race('DawnstarSmallShipFaction', 'YASSailorRace')
    ctx.set_faction_race('DLC2WaterStoneSailors', 'YASSailorRace')
    ctx.set_faction_race('SailorFaction', 'YASSailorRace')
    ctx.set_faction_race('ShipsNorthwindFaction', 'YASSailorRace')
    ctx.set_faction_race('ShipsRedWaveFaction', 'YASSailorRace')
    ctx.set_faction_race('ShipsSeaSquallFaction', 'YASSailorRace')
    ctx.set_npc_race('Jolf', 'YASSailorRace')

    # ===================================================================
    # Headpart equivalents and labels
    # Ported from BDFurrySkyrimRaceDefs.pas
    # ===================================================================

    _configure_eye_equivalents(ctx)
    _configure_scar_equivalents(ctx)
    _configure_hair_labels(ctx)


def _configure_eye_equivalents(ctx):
    """Map vanilla eyes to furry eyes."""
    a = ctx.assign_headpart

    # =========== Male human eyes → DayPred ===========
    a('MaleEyesHumanAmber', 'YASDayPredMaleEyesAmber')
    a('MaleEyesHumanAmberBlindRight', 'YASDayPredMaleEyesAlbino')
    a('MaleEyesHumanBlind', 'YASDayPredMaleEyesBlind')
    a('MaleEyesHumanBrightGreen', 'YASDayPredMaleEyesGreen')
    a('MaleEyesHumanBrightGreenBlindRight', 'YASDayPredMaleEyesGreen')
    a('MaleEyesHumanBrown', 'YASDayPredMaleEyesBrownDark')
    a('MaleEyesHumanBrownBlindLeft', 'YASDayPredMaleEyesAmberBlindL')
    a('MaleEyesHumanBrownBlindRight', 'YASDayPredMaleEyesAmberBlindR')
    a('MaleEyesHumanBrownBloodShot', 'YASDayPredMaleEyesBrownDark')
    a('MaleEyesHumanDarkBlue', 'YASDayPredMaleEyesBlueDark')
    a('MaleEyesHumanDemon', 'YASDayPredMaleEyesRed')
    a('MaleEyesHumanGreenHazelLeft', 'YASDayPredMaleEyesMixBlueBrown')
    a('MaleEyesHumanGrey', 'YASDayPredMaleEyesGrey')
    a('MaleEyesHumanHazel', 'YASDayPredMaleEyesYellow')
    a('MaleEyesHumanHazelBrown', 'YASDayPredMaleEyesMixYellowGreen')
    a('MaleEyesHumanIceBlue', 'YASDayPredMaleEyesBlue')
    a('MaleEyesHumanLightBlue', 'YASDayPredMaleEyesSnow')
    a('MaleEyesHumanLightBlueBlindLeft', 'YASDayPredMaleEyesBlueGreyBlindL')
    a('MaleEyesHumanLightBlueBloodShot', 'YASDayPredMaleEyesSnow')
    a('MaleEyesHumanLightGrey', 'YASDayPredMaleEyesGrey')
    a('MaleEyesHumanLightIceGreyBlindLeft', 'YASDayPredMaleEyesGreenBlindL')
    a('MaleEyesHumanVampire', 'YASDayPredMaleEyesVampire')

    # =========== Female human eyes → DayPred ===========
    a('FemaleEyesHumanAmber', 'YASDayPredFemEyesAmber')
    a('FemaleEyesHumanAmberBlindLeft', 'YASDayPredFemEyesBlueBlindL')
    a('FemaleEyesHumanBlind', 'YASDayPredFemEyesBlind')
    a('FemaleEyesHumanBrightGreen', 'YASDayPredFemEyesGreen')
    a('FemaleEyesHumanBrown', 'YASDayPredFemEyesBrownDark')
    a('FemaleEyesHumanBrownBlindRight', 'YASDayPredMaleEyesAmberBlindR')
    a('FemaleEyesHumanBrownBloodShot', 'YASDayPredFemEyesRed')
    a('FemaleEyesHumanDarkBlue', 'YASDayPredFemEyesBlue')
    a('FemaleEyesHumanDarkBlueBlindRight', 'YASDayPredFemEyesGreenBlindR')
    a('FemaleEyesHumanDemon', 'YASNightPredFemEyesRedNarrow')
    a('FemaleEyesHumanGreenHazel', 'YASDayPredFemEyesGreen')
    a('FemaleEyesHumanGrey', 'YASDayPredFemEyesLilac')
    a('FemaleEyesHumanGreyBlindLeft', 'YASDayPredFemEyesGreenBlindL')
    a('FemaleEyesHumanHazel', 'YASDayPredFemEyesAmber')
    a('FemaleEyesHumanHazelBrown', 'YASDayPredFemEyesAmber')
    a('FemaleEyesHumanIceBlue', 'YASDayPredFemEyesAlbino')
    a('FemaleEyesHumanLightBlue', 'YASDayPredFemEyesBlueDark')
    a('FemaleEyesHumanLightBlueBloodShot', 'YASDayPredFemEyesRed')
    a('FemaleEyesHumanLightGrey', 'YASDayPredFemEyesAlbino')
    a('FemaleEyesHumanVampire', 'YASDayPredFemEyesVampire')
    a('FemaleEyesHumanYellow', 'YASDayPredFemEyesYellow')

    # =========== Female dark elf eyes → NightPred ===========
    a('FemaleEyesDarkElfBlind', 'YASDayPredFemEyesBlind')
    a('FemaleEyesDarkElfDeepRed', 'YASNightPredFemEyesRed')
    a('FemaleEyesDarkElfDeepRed2', 'YASNightPredFemEyesGreen')
    a('FemaleEyesDarkElfDeepRed2BlindRight', 'YASNightPredFemEyesAmberBlindR')
    a('FemaleEyesDarkElfDeepRedBlindLeft', 'YASDayPredFemEyesAmberBlindL')
    a('FemaleEyesDarkElfRed', 'YASNightPredFemEyesRed')
    a('FemaleEyesDarkElfUnique', 'YASNightPredFemEyesGreen')
    a('FemaleEyesDremora', 'YASNIghtPredFemEyesOrangeNarrow')

    # =========== Female high elf eyes ===========
    a('FemaleEyesHighElfDarkYellow', 'YASDayPredFemEyesGold')
    a('FemaleEyesHighElfOrange', 'YASDayPredFemEyesGold')
    a('FemaleEyesHighElfOrangeBlindRight', 'YASDayPredFemEyesGreenBlindR')
    a('FemaleEyesHighElfYellow', 'YASDayPredFemEyesYellow')
    a('FemaleEyesHighElfYellowBlindLeft', 'YASDayPredFemEyesAmberBlindL')

    # =========== Female elf misc ===========
    a('FemaleEyesElfBlind', 'YASDayPredFemEyesBlind')

    # =========== Female orc eyes ===========
    a('FemaleEyesOrcBlind', 'YASDayPredFemEyesBlind')
    a('FemaleEyesOrcDarkGrey', 'YASDayPredFemEyesAlbino')
    a('FemaleEyesOrcIceBlue', 'YASDayPredFemEyesBlueDark')
    a('FemaleEyesOrcIceBlueBlindRight', 'YASDayPredFemEyesGreenBlindR')
    a('FemaleEyesOrcRed', 'YASDayPredFemEyesBlind')
    a('FemaleEyesOrcRedBlindRight', 'YASDayPredFemEyesRedBlindR')
    a('FemaleEyesOrcVampire', 'YASDayPredFemEyesVampire')
    a('FemaleEyesOrcYellow', 'YASDayPredFemEyesYellow')
    a('FemaleEyesOrcYellowBlindLeft', 'YASNightPredFemEyesYellowBlindLeft')

    # =========== Female wood elf eyes → NightPred ===========
    a('FemaleEyesWoodElfBlind', 'YASDayPredFemEyesBlind')
    a('FemaleEyesWoodElfBrown', 'YASNightPredFemEyesBrown')
    a('FemaleEyesWoodElfDeepBrown', 'YASNightPredFemEyesBrownDark')
    a('FemaleEyesWoodElfDeepBrownBlindLeft', 'YASNightPredFemEyesYellowBlindLeft')
    a('FemaleEyesWoodElfDeepViolet', 'YASNIghtPredFemEyesIce')
    a('FemaleEyesWoodElfDeepVioletBlindRight', 'YASNightPredFemEyesYellowBlindR')
    a('FemaleEyesWoodElfLightBrown', 'YASNIghtPredFemEyesAmberNarrow')


def _configure_scar_equivalents(ctx):
    """Map vanilla scars to furry scars by race."""
    a = ctx.assign_headpart

    # =========== LYKAIOS scars ===========
    a('MarksFemaleHumanoid10RightGashR', 'YASLykaiosFemScarC01')
    a('MarksFemaleHumanoid05LeftGash', 'YASLykaiosFemScarC01')
    a('MarksFemaleHumanoid11LeftGashR', 'YASLykaiosFemScarC02')
    a('MarksFemaleHumanoid12LeftGashR', 'YASLykaiosFemScarC02')
    a('MarksFemaleHumanoid06LeftGash', 'YASLykaiosFemScarC02')
    a('MarksFemaleHumanoid01LeftGash', 'YASLykaiosFemScarL01')
    a('MarksFemaleHumanoid11LeftGash', 'YASLykaiosFemScarL01')
    a('MarksFemaleHumanoid02LeftGash', 'YASLykaiosFemScarL02')
    a('MarksFemaleHumanoid03LeftGash', 'YASLykaiosFemScarL03')
    a('MarksFemaleHumanoid10LeftGash', 'YASLykaiosFemScarL03')
    a('MarksFemaleHumanoid12LeftGash', 'YASLykaiosFemScarL03')
    a('MarksFemaleHumanoid04LeftGash', 'YASLykaiosFemScarL04')
    a('MarksFemaleHumanoid07RightGash', 'YASLykaiosFemScarR01')
    a('MarksFemaleHumanoid08RightGash', 'YASLykaiosFemScarR02')
    a('MarksFemaleHumanoid09RightGash', 'YASLykaiosFemScarR03')
    a('MarksMaleHumanoid12LeftGash', 'YASLykMaleScarC09')
    a('MarksMaleHumanoid11RightGashR', 'YASLykMaleScarC09')
    a('MarksMaleHumanoid12RightGashR', 'YASLykMaleScarC10')
    a('MarksMaleHumanoid03LeftGash', 'YASLykMaleScarL05LBlindL')
    a('MarksMaleHumanoid10LeftGash', 'YASLykMaleScarL05LBlindL')
    a('MarksMaleHumanoid01LeftGash', 'YASLykMaleScarL06')
    a('MarksMaleHumanoid05LeftGash', 'YASLykMaleScarL06')
    a('MarksMaleHumanoid02LeftGash', 'YASLykMaleScarL07')
    a('MarksMaleHumanoid04LeftGash', 'YASLykMaleScarL08')
    a('MarksMaleHumanoid06LeftGash', 'YASLykMaleScarL08')
    a('MarksMaleHumanoid11LeftGash', 'YASLykMaleScarL08')
    a('MarksMaleHumanoid09RightGash', 'YASLykMaleScarR01')
    a('MarksMaleHumanoid04RightGashR', 'YASLykMaleScarR01')
    a('MarksMaleHumanoid06RightGashR', 'YASLykMaleScarR03BlindR')
    a('MarksMaleHumanoid07RightGash', 'YASLykMaleScarR04')
    a('MarksMaleHumanoid08RightGash', 'YASLykMaleScarR04')
    a('MarksMaleHumanoid10RightGashR', 'YASLykMaleScarR04')

    # =========== KETTU scars ===========
    a('MarksFemaleHumanoid10RightGashR', 'YASKettuFemScarC01')
    a('MarksFemaleHumanoid05LeftGash', 'YASKettuFemScarC01')
    a('MarksFemaleHumanoid11LeftGashR', 'YASKettuFemScarC02')
    a('MarksFemaleHumanoid12LeftGashR', 'YASKettuFemScarC02')
    a('MarksFemaleHumanoid06LeftGash', 'YASKettuFemScarC02')
    a('MarksFemaleHumanoid01LeftGash', 'YASKettuFemScarL01')
    a('MarksFemaleHumanoid11LeftGash', 'YASKettuFemScarL01')
    a('MarksFemaleHumanoid02LeftGash', 'YASKettuFemScarL02')
    a('MarksFemaleHumanoid03LeftGash', 'YASKettuFemScarL03')
    a('MarksFemaleHumanoid10LeftGash', 'YASKettuFemScarL03')
    a('MarksFemaleHumanoid12LeftGash', 'YASKettuFemScarL03')
    a('MarksFemaleHumanoid04LeftGash', 'YASKettuFemScarL04')
    a('MarksFemaleHumanoid07RightGash', 'YASKettuFemScarR01')
    a('MarksFemaleHumanoid08RightGash', 'YASKettuFemScarR02')
    a('MarksFemaleHumanoid09RightGash', 'YASKettuFemScarR03')
    a('MarksMaleHumanoid12LeftGash', 'YASKettuMaleScarC02')
    a('MarksMaleHumanoid11RightGashR', 'YASKettuMaleScarC02')
    a('MarksMaleHumanoid01LeftGash', 'YASKettuMaleScarL01')
    a('MarksMaleHumanoid05LeftGash', 'YASKettuMaleScarL01')
    a('MarksMaleHumanoid02LeftGash', 'YASKettuMaleScarL02')
    a('MarksMaleHumanoid06LeftGash', 'YASKettuMaleScarL02')
    a('MarksMaleHumanoid03LeftGash', 'YASKettuMaleScarL03BlindL')
    a('MarksMaleHumanoid10LeftGash', 'YASKettuMaleScarL03BlindL')
    a('MarksMaleHumanoid04LeftGash', 'YASKettuMaleScarL04')
    a('MarksMaleHumanoid11LeftGash', 'YASKettuMaleScarL04')
    a('MarksMaleHumanoid09RightGash', 'YASKettuMaleScarR01')
    a('MarksMaleHumanoid04RightGashR', 'YASKettuMaleScarR01')
    a('MarksMaleHumanoid06RightGashR', 'YASKettuMaleScarR02BlindR')
    a('MarksMaleHumanoid07RightGash', 'YASKettuMaleScarR03')
    a('MarksMaleHumanoid10RightGashR', 'YASKettuMaleScarR03')
    a('MarksMaleHumanoid08RightGash', 'YASKettuMaleScarR04')

    # =========== KONOI scars ===========
    a('MarksFemaleHumanoid10RightGashR', 'YASKonoiFemScarC01')
    a('MarksFemaleHumanoid05LeftGash', 'YASKonoiFemScarC01')
    a('MarksFemaleHumanoid11LeftGashR', 'YASKonoiFemScarC02')
    a('MarksFemaleHumanoid12LeftGashR', 'YASKonoiFemScarC02')
    a('MarksFemaleHumanoid06LeftGash', 'YASKonoiFemScarC02')
    a('MarksFemaleHumanoid01LeftGash', 'YASKonoiFemScarL01')
    a('MarksFemaleHumanoid11LeftGash', 'YASKonoiFemScarL01')
    a('MarksFemaleHumanoid02LeftGash', 'YASKonoiFemScarL02')
    a('MarksFemaleHumanoid03LeftGash', 'YASKonoiFemScarL03')
    a('MarksFemaleHumanoid10LeftGash', 'YASKonoiFemScarL03')
    a('MarksFemaleHumanoid12LeftGash', 'YASKonoiFemScarL03')
    a('MarksFemaleHumanoid04LeftGash', 'YASKonoiFemScarL04')
    a('MarksFemaleHumanoid07RightGash', 'YASKonoiFemScarR01')
    a('MarksFemaleHumanoid08RightGash', 'YASKonoiFemScarR02')
    a('MarksFemaleHumanoid09RightGash', 'YASKonoiFemScarR03')

    # =========== KYGARRA scars ===========
    a('MarksFemaleHumanoid10RightGashR', 'YASKygarraFemScarC01')
    a('MarksFemaleHumanoid05LeftGash', 'YASKygarraFemScarC01')
    a('MarksFemaleHumanoid11LeftGashR', 'YASKygarraFemScarC02')
    a('MarksFemaleHumanoid12LeftGashR', 'YASKygarraFemScarC02')
    a('MarksFemaleHumanoid06LeftGash', 'YASKygarraFemScarC02')
    a('MarksFemaleHumanoid01LeftGash', 'YASKygarraFemScarL01')
    a('MarksFemaleHumanoid11LeftGash', 'YASKygarraFemScarL01')
    a('MarksFemaleHumanoid02LeftGash', 'YASKygarraFemScarL02')
    a('MarksFemaleHumanoid03LeftGash', 'YASKygarraFemScarL03')
    a('MarksFemaleHumanoid10LeftGash', 'YASKygarraFemScarL03')
    a('MarksFemaleHumanoid12LeftGash', 'YASKygarraFemScarL03')
    a('MarksFemaleHumanoid04LeftGash', 'YASKygarraFemScarL04')
    a('MarksFemaleHumanoid07RightGash', 'YASKygarraFemScarR01')
    a('MarksFemaleHumanoid08RightGash', 'YASKygarraFemScarR02')
    a('MarksFemaleHumanoid09RightGash', 'YASKygarraFemScarR03')
    a('MarksMaleHumanoid12LeftGash', 'YASKygarraMaleScarC01')
    a('MarksMaleHumanoid11RightGashR', 'YASKygarraMaleScarC01')
    a('MarksMaleHumanoid12RightGashR', 'YASKygarraMaleScarC02')
    a('MarksMaleHumanoid01LeftGash', 'YASKygarraMaleScarL01')
    a('MarksMaleHumanoid05LeftGash', 'YASKygarraMaleScarL01')
    a('MarksMaleHumanoid02LeftGash', 'YASKygarraMaleScarL02')
    a('MarksMaleHumanoid06LeftGash', 'YASKygarraMaleScarL02')
    a('MarksMaleHumanoid03LeftGash', 'YASKygarraMaleScarL03')
    a('MarksMaleHumanoid10LeftGash', 'YASKygarraMaleScarL03')
    a('MarksMaleHumanoid04LeftGash', 'YASKygarraMaleScarL04')
    a('MarksMaleHumanoid11LeftGash', 'YASKygarraMaleScarL04')
    a('MarksMaleHumanoid09RightGash', 'YASKygarraMaleScarR01')
    a('MarksMaleHumanoid04RightGashR', 'YASKygarraMaleScarR01')
    a('MarksMaleHumanoid06RightGashR', 'YASKygarraMaleScarR02')
    a('MarksMaleHumanoid07RightGash', 'YASKygarraMaleScarR03')
    a('MarksMaleHumanoid10RightGashR', 'YASKygarraMaleScarR03')
    a('MarksMaleHumanoid08RightGash', 'YASKygarraMaleScarR04')

    # =========== VAALSARK scars ===========
    a('MarksFemaleHumanoid10RightGashR', 'YASVaalsarkFemScarC01')
    a('MarksFemaleHumanoid05LeftGash', 'YASVaalsarkFemScarC01')
    a('MarksFemaleHumanoid11LeftGashR', 'YASVaalsarkFemScarC02')
    a('MarksFemaleHumanoid12LeftGashR', 'YASVaalsarkFemScarC02')
    a('MarksFemaleHumanoid06LeftGash', 'YASVaalsarkFemScarC02')
    a('MarksFemaleHumanoid01LeftGash', 'YASVaalsarkFemScarL01')
    a('MarksFemaleHumanoid11LeftGash', 'YASVaalsarkFemScarL01')
    a('MarksFemaleHumanoid02LeftGash', 'YASVaalsarkFemScarL02')
    a('MarksFemaleHumanoid03LeftGash', 'YASVaalsarkFemScarL03')
    a('MarksFemaleHumanoid10LeftGash', 'YASVaalsarkFemScarL03')
    a('MarksFemaleHumanoid12LeftGash', 'YASVaalsarkFemScarL03')
    a('MarksFemaleHumanoid04LeftGash', 'YASVaalsarkFemScarL04')
    a('MarksFemaleHumanoid07RightGash', 'YASVaalsarkFemScarR01')
    a('MarksFemaleHumanoid08RightGash', 'YASVaalsarkFemScarR02')
    a('MarksFemaleHumanoid09RightGash', 'YASVaalsarkFemScarR03')
    a('MarksMaleHumanoid12LeftGash', 'YASVaalsarkMaleScarC01')
    a('MarksMaleHumanoid11RightGashR', 'YASVaalsarkMaleScarC01')
    a('MarksMaleHumanoid12RightGashR', 'YASVaalsarkMaleScarC02')
    a('MarksMaleHumanoid01LeftGash', 'YASVaalsarkMaleScarL01')
    a('MarksMaleHumanoid05LeftGash', 'YASVaalsarkMaleScarL01')
    a('MarksMaleHumanoid02LeftGash', 'YASVaalsarkMaleScarL02')
    a('MarksMaleHumanoid06LeftGash', 'YASVaalsarkMaleScarL02')
    a('MarksMaleHumanoid03LeftGash', 'YASVaalsarkMaleScarL03BlindL')
    a('MarksMaleHumanoid10LeftGash', 'YASVaalsarkMaleScarL03BlindL')
    a('MarksMaleHumanoid04LeftGash', 'YASVaalsarkMaleScarL04')
    a('MarksMaleHumanoid11LeftGash', 'YASVaalsarkMaleScarL04')
    a('MarksMaleHumanoid09RightGash', 'YASVaalsarkMaleScarR01')
    a('MarksMaleHumanoid04RightGashR', 'YASVaalsarkMaleScarR01')
    a('MarksMaleHumanoid06RightGashR', 'YASVaalsarkMaleScarR02')
    a('MarksMaleHumanoid07RightGash', 'YASVaalsarkMaleScarR03')
    a('MarksMaleHumanoid10RightGashR', 'YASVaalsarkMaleScarR03')
    a('MarksMaleHumanoid08RightGash', 'YASVaalsarkMaleScarR04')
    a('MarksMaleHumanoid08RightGash', 'YASVaalsarkMaleScarR05BlindR')

    # =========== XEBA scars ===========
    a('MarksFemaleHumanoid10RightGashR', 'YASXebaFemScarC01')
    a('MarksFemaleHumanoid05LeftGash', 'YASXebaFemScarC01')
    a('MarksFemaleHumanoid11LeftGashR', 'YASXebaFemScarC02')
    a('MarksFemaleHumanoid12LeftGashR', 'YASXebaFemScarC02')
    a('MarksFemaleHumanoid06LeftGash', 'YASXebaFemScarC02')
    a('MarksFemaleHumanoid01LeftGash', 'YASXebaFemScarL01')
    a('MarksFemaleHumanoid11LeftGash', 'YASXebaFemScarL01')
    a('MarksFemaleHumanoid02LeftGash', 'YASXebaFemScarL02')
    a('MarksFemaleHumanoid03LeftGash', 'YASXebaFemScarL03')
    a('MarksFemaleHumanoid10LeftGash', 'YASXebaFemScarL03')
    a('MarksFemaleHumanoid12LeftGash', 'YASXebaFemScarL03')
    a('MarksFemaleHumanoid04LeftGash', 'YASXebaFemScarL04')
    a('MarksFemaleHumanoid07RightGash', 'YASXebaFemScarR01')
    a('MarksFemaleHumanoid08RightGash', 'YASXebaFemScarR02')
    a('MarksFemaleHumanoid09RightGash', 'YASXebaFemScarR03')


def _configure_hair_labels(ctx):
    """Label furry hair headparts for label-based matching."""
    lbl = ctx.label_headpart_list

    # =========== Dog male hair ===========
    lbl('YASDogMaleHairDreads001', 'DREADS,BOLD,FUNKY,LONG')
    lbl('YASDogMaleHairDreads003', 'DREADS,NOBLE,BOLD,FUNKY,LONG')
    lbl('YASDogMaleHairDreadsFringe', 'DREADS,NOBLE,BOLD,FUNKY,YOUNG,LONG')
    lbl('YASDogMaleHairDreadsHeadband', 'DREADS,NOBLE,BOLD,FUNKY,FEATHERS,LONG')
    lbl('YASDogMaleHairFringeFlip001', 'YOUNG,SHORT')
    lbl('YASDogMaleHairLionMane001', 'MANE,LONG')
    lbl('YASDogMaleHairLionMane002', 'MANE,LONG,YOUNG')
    lbl('YASDogMaleHairLionManebraids', 'MANE,LONG,NOBLE,BRAIDS')
    lbl('YASDogMaleHairLionManeFringeLeftBraid', 'MANE,LONG,NOBLE,BRAIDS')
    lbl('YASDogMaleHairLionManeHeadband', 'MANE,LONG,NOBLE,FEATHERS')
    lbl('YASDogMaleHairLongBraid001', 'BRAIDS,NEAT,TIEDBACK')
    lbl('YASDogMaleHairLongBraid002', 'TIEDBACK,BRAIDS,NOBLE')
    lbl('YASDogMaleHairLongBraidleft', 'NEAT,TIEDBACK,BRAIDS,NOBLE')
    lbl('YASDogMaleHairMohawk001', 'MOHAWK,BRAIDS,MILITARY,BOLD')
    lbl('YASDogMaleHairMohawk003', 'MOHAWK,FEATHERS,BOLD')
    lbl('YASDogMaleHairMohawkFringe', 'MOHAWK,YOUNG,BOLD')
    lbl('YASDogMaleHairShaggyHair002', 'LONG,MESSY')
    lbl('YASDogMaleHairShaggyHair003', 'LONG,MESSY,FEATHERS')
    lbl('YASDogMaleHairShorCrop001', 'SHORT,NEAT')
    lbl('YASDogMaleHairShorCrop002', 'SHORT,NEAT,YOUNG')
    lbl('YASDogMaleHairShorCrop003', 'SHORT,NEAT,NOBLE')
    lbl('YASDogMaleHairShorCrop004', 'SHORT,NEAT,NOBLE,FEATHERS')
    lbl('YASDogMaleHairTiedStyle001', 'LONG,NOBLE,NEAT')
    lbl('YASDogMaleHairTiedStyleFringe', 'LONG,NOBLE,NEAT,YOUNG')
    lbl('YASDogMaleHairTiedStyleHeadband', 'LONG,NOBLE,NEAT,YOUNG,FEATHERS')
    lbl('YASDogMaleHairVanillaBraid001', 'LONG,NEAT,TIEDBACK')
    lbl('YASDogMaleHairVanillaHair001', 'MESSY,LONG')
    lbl('YASDogMaleHairSidehawk', 'MOHAWK,FUNKY,BOLD')
    lbl('YASDogMaleHairImperial01', 'SHORT,NEAT,MILITARY')

    # =========== Dog female hair ===========
    lbl('YASDogFemHair01', 'NEAT,TIEDBACK,SHORT,BRAIDS')
    lbl('YASDogFemHair02', 'NEAT,TIEDBACK')
    lbl('YASDogFemHair03', 'NEAT,SHORT')
    lbl('YASDogFemHair04', 'NEAT,LONG,TIEDBACK,BRAIDS')
    lbl('YASDogFemHair05', 'SHORT,TIEDBACK,FUNKY')
    lbl('YASDogFemHair06', 'SHORT,TIEDBACK,FUNKY')
    lbl('YASDogFemHair07', 'SHORT,TIEDBACK,FUNKY,BRAIDS')
    lbl('YASDogFemHair08', 'NEAT,LONG,TIEDBACK,BRAIDS,FUNKY')
    lbl('YASDogFemHair09', 'NEAT,TIEDBACK,SHORT,BRAIDS')
    lbl('YASDogFemHair10', 'NEAT,TIEDBACK')
    lbl('YASDogFemHairBraid001', 'NEAT,TIEDBACK,LONG,BRAIDS')
    lbl('YASDogFemHairBraid002', 'NEAT,TIEDBACK,LONG,BRAIDS,NOBLE')
    lbl('YASDogFemHairDreads001', 'DREADS,BOLD,FUNKY,LONG')
    lbl('YASDogFemHairDreads002', 'DREADS,BOLD,FUNKY,NOBLE,ELABORATE,LONG')
    lbl('YASDogFemHairDreads003', 'DREADS,BOLD,FUNKY,LONG')
    lbl('YASDogFemHairDreads004', 'DREADS,BOLD,FUNKY,NOBLE,ELABORATE,LONG')
    lbl('YASDogFemHairFringeFlip001', 'YOUNG,NEAT,SHORT')
    lbl('YASDogFemHairMane001', 'MANE,LONG,BOLD')
    lbl('YASDogFemHairMane002', 'MANE,LONG,BOLD')
    lbl('YASDogFemHairMane003', 'MANE,LONG,BOLD,NOBLE')
    lbl('YASDogFemHairMohawk001', 'MOHAWK,BOLD,FUNKY')
    lbl('YASDogFemHairMohawk002', 'MOHAWK,BOLD,FUNKY,FEATHERS')
    lbl('YASDogFemHairShaggy001', 'LONG,MESSY')
    lbl('YASDogFemHairShaggy002', 'MESSY,BRAIDS')
    lbl('YASDogFemHairShortCrop001', 'SHORT,NEAT,MILITARY')
    lbl('YASDogFemHairShortCrop002', 'SHORT,NEAT')
    lbl('YASDogFemHairShortCrop003', 'SHORT,NEAT,BRAIDS,NOBLE')
    lbl('YASDogFemHairTiedStyle001', 'LONG,NOBLE,ELABORATE')
    lbl('YASDogFemHairVanillaBraid001', 'TIEDBACK,BRAIDS')
    lbl('YASDogFemHairVanillaCrop001', 'SHORT,TIEDBACK')
    lbl('YASDogFemHairVanillaHair001', 'SHORT,BRAIDS,FUNKY')
    lbl('YASFemHairApachii01', 'NEAT,YOUNG,BRAIDS')
    lbl('YASFemHairApachii02', 'DREADS,LONG,BOLD,FUNKY')
    lbl('YASFemHairApachii03', 'NEAT,SHORT')
    lbl('YASFemHairApachii04', 'MESSY,LONG')
    lbl('YASFemHairApachii05', 'MESSY,LONG')

    # =========== Cat male hair ===========
    lbl('YASCatMaleHairDreads001', 'DREADS,BOLD,FUNKY,LONG')
    lbl('YASCatMaleHairDreads003', 'DREADS,NOBLE,BOLD,FUNKY,LONG')
    lbl('YASCatMaleHairDreadsFringe', 'DREADS,NOBLE,BOLD,FUNKY,YOUNG,LONG')
    lbl('YASCatMaleHairDreadsHeadband', 'DREADS,NOBLE,BOLD,FUNKY,FEATHERS,LONG')
    lbl('YASCatMaleHairFringeFlip001', 'YOUNG,SHORT')
    lbl('YASCatMaleHairLionMane001', 'MANE,LONG')
    lbl('YASCatMaleHairLionMane002', 'MANE,LONG,YOUNG')
    lbl('YASCatMaleHairLionManebraids', 'MANE,LONG,NOBLE,BRAIDS')
    lbl('YASCatMaleHairLionManeFringeLeftBraid', 'MANE,LONG,NOBLE,BRAIDS')
    lbl('YASCatMaleHairLionManeHeadband', 'MANE,LONG,NOBLE,FEATHERS')
    lbl('YASCatMaleHairLongBraid001', 'BRAIDS,NEAT,TIEDBACK')
    lbl('YASCatMaleHairLongBraid002', 'TIEDBACK,BRAIDS,NOBLE')
    lbl('YASCatMaleHairLongBraidleft', 'NEAT,TIEDBACK,BRAIDS,NOBLE')
    lbl('YASCatMaleHairMohawk001', 'MOHAWK,BRAIDS,MILITARY,BOLD')
    lbl('YASCatMaleHairMohawk003', 'MOHAWK,FEATHERS,BOLD')
    lbl('YASCatMaleHairMohawkFringe', 'MOHAWK,YOUNG,BOLD')
    lbl('YASCatMaleHairShaggyHair002', 'LONG,MESSY')
    lbl('YASCatMaleHairShaggyHair003', 'LONG,MESSY,FEATHERS')
    lbl('YASCatMaleHairShorCrop001', 'SHORT,NEAT')
    lbl('YASCatMaleHairShorCrop002', 'SHORT,NEAT,YOUNG')
    lbl('YASCatMaleHairShorCrop003', 'SHORT,NEAT,NOBLE')
    lbl('YASCatMaleHairShorCrop004', 'SHORT,NEAT,NOBLE,FEATHERS')
    lbl('YASCatMaleHairTiedStyle001', 'LONG,NOBLE,NEAT')
    lbl('YASCatMaleHairTiedStyleFringe', 'LONG,NOBLE,NEAT,YOUNG')
    lbl('YASCatMaleHairTiedStyleHeadband', 'LONG,NOBLE,NEAT,YOUNG,FEATHERS')
    lbl('YASCatMaleHairVanillaBraid001', 'LONG,NEAT,TIEDBACK')
    lbl('YASCatMaleHairVanillaHair001', 'MESSY,LONG')
    lbl('YASCatMaleHairSidehawk', 'MOHAWK,FUNKY,BOLD')

    # =========== Cat female hair ===========
    lbl('YASCatFemHairBraid001', 'NEAT,TIEDBACK,LONG,BRAIDS')
    lbl('YASCatFemHairBraid002', 'NEAT,TIEDBACK,LONG,BRAIDS,NOBLE')
    lbl('YASCatFemHairDreads001', 'DREADS,BOLD,FUNKY,LONG')
    lbl('YASCatFemHairDreads002', 'DREADS,BOLD,FUNKY,NOBLE,ELABORATE,LONG')
    lbl('YASCatFemHairDreads003', 'DREADS,BOLD,FUNKY,LONG')
    lbl('YASCatFemHairDreads004', 'DREADS,BOLD,FUNKY,NOBLE,ELABORATE,LONG')
    lbl('YASCatFemHairFringeFlip001', 'YOUNG,NEAT,SHORT')
    lbl('YASCatFemHairMane001', 'MANE,LONG,BOLD')
    lbl('YASCatFemHairMane002', 'MANE,LONG,BOLD')
    lbl('YASCatFemHairMane003', 'MANE,LONG,BOLD,NOBLE')
    lbl('YASCatFemHairMohawk001', 'MOHAWK,BOLD,FUNKY')
    lbl('YASCatFemHairMohawk002', 'MOHAWK,BOLD,FUNKY,FEATHERS')
    lbl('YASCatFemHairShaggy001', 'LONG,MESSY')
    lbl('YASCatFemHairShaggy002', 'MESSY,BRAIDS')
    lbl('YASCatFemHairShortCrop001', 'SHORT,NEAT,MILITARY')
    lbl('YASCatFemHairShortCrop002', 'SHORT,NEAT')
    lbl('YASCatFemHairShortCrop003', 'SHORT,NEAT,BRAIDS,NOBLE')
    lbl('YASCatFemHairTiedStyle001', 'LONG,NOBLE,ELABORATE')
    lbl('YASCatFemHairVanillaBraid001', 'TIEDBACK,BRAIDS')
    lbl('YASCatFemHairVanillaCrop001', 'SHORT,TIEDBACK')
    lbl('YASCatFemHairVanillaHair001', 'SHORT,BRAIDS,FUNKY')
    lbl('YASCatFemHairApachii01', 'NEAT,YOUNG,BRAIDS')
    lbl('YASCatFemHairApachii02', 'DREADS,LONG,BOLD,FUNKY')
    lbl('YASCatFemHairApachii03', 'NEAT,SHORT')
    lbl('YASCatFemHairApachii04', 'MESSY,LONG')
    lbl('YASCatFemHairApachii05', 'MESSY,LONG')

    # =========== Otter hair ===========
    lbl('HairCellanMale01', 'BRAIDS,NEAT')
    lbl('HairCellanMale02', 'BRAIDS,TIEDBACK')
    lbl('HairCellanMale03', 'FUNKY,MOHAWK')
    lbl('HairCellanMale04', 'BRAIDS')
    lbl('HairCellanFemale01', 'BRAIDS')
    lbl('HairCellanFemale02', 'SHORT')
    lbl('HairCellanFemale04', 'LONG,NEAT,BRAIDS')
